compile:
	g++ main.cpp -o main.exe -losg -losgDB -losgViewer -losgGA -losgParticle -losgShadow

compare:
	g++ main.cpp -o main2.exe -losg -losgDB -losgViewer -losgGA -losgParticle -losgShadow

clear:
	rm main.exe

clear_c:
	rm main.exe
	rm main2.exe
