compile:
	g++ -Wall -c TP1points.cpp GeometricObjects.cpp Circle.cpp -lGL -lGLU -lglut -lGLEW
	g++ -Wall TP1points.o GeometricObjects.o Circle.o -o main.exe -lGL -lGLU -lglut -lGLEW

clean:
	rm *.o
	rm main.exe
